### ISSUE TITLE
Answers are not registering

### ISSUE THREAD

**Issue by bkhoward2001** [brainboxdotcc/triviabot#14]
I have installed Trivia bot on discord, and everything seems to work, ie. it starts the game, gives the hints, etc.

However, even though I am putting in the right answer, it is not saying or registering that it was answered correctly... I have switched to other account and answered not as the admin, and same. No matter how many correct answers were typed, at the end of the game it says that no one answered any correctly.

**Comment by HolyAcid** [comment]
Hi. This isn't a coding bug and doesn't need to be reported here. Your bot permissions likely aren't set up properly in your server. Please visit our Brainbox.cc discord server and we'll be happy to help you figure it out.

https://discord.gg/6j8eRaAY
